### ISSUE TITLE
 Don't work on android 10?

### ISSUE THREAD

**Issue by Oliro** [thanh-nguyen-kim/Unity_Android_Screen_Recorder#12]
When I trying to record on android 10, the app closes after permission accepted. Any idea?

**Comment by thanh-nguyen-kim** [comment]
I have not tested in android 10 yet. This project is so out date. You can use "natcord", it is very good plugin to record screen in both android and iOS

**Comment by thanh-nguyen-kim** [comment]
The new plugin update now support Android 10.

**Comment by Oliro** [comment]
Em sáb, 14 de nov de 2020 11:01, Tee <notifications@github.com> escreveu:
