### ISSUE TITLE
App Crash on Android 10

### ISSUE THREAD

**Issue by ThePacerJ** [thanh-nguyen-kim/Unity_Android_Screen_Recorder#13]
Hello,
application is properly build from Unity,but when i open app in my phone(Oneplus 6(Android 10))it crashes.
Please let me know if there is a fix for this issue.
Thank You.

**Comment by thanh-nguyen-kim** [comment]
Can you show me the manifest in Plugin/Android.
You may need to replace ".AndroidUtils" with "com.setik.androidutils.AndroidUtils"
Hope this will fix your problem.

**Comment by ThePacerJ** [comment]
I'll try this and Update you.

**Comment by ThePacerJ** [comment]
[AndroidManifest.txt](https://github.com/thanh-nguyen-kim/Unity_Android_Screen_Recorder/files/5542788/AndroidManifest.txt)

**Comment by thanh-nguyen-kim** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest 
  xmlns:android="http://schemas.android.com/apk/res/android" package="com.setik.androidutils">
  <application android:icon="@drawable/app_icon" android:label="@string/app_name">
    <activity android:name="com.setik.androidutils.AndroidUtils" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
    <meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="true" />
  </application>
</manifest>

**Comment by thanh-nguyen-kim** [comment]
Try this manifest. if it is still crashing, could you open "logcat" and show me the log message

**Comment by ThePacerJ** [comment]
Thank You so much brother,It is working perfectly.
