### ISSUE TITLE
Usage with other main activiy

### ISSUE THREAD

**Issue by SidiaDevelopment** [thanh-nguyen-kim/Unity_Android_Screen_Recorder#17]
Hello,

I am currently using firebase and it already defines MAIN and LAUNCHER activities for my unity project.

If I define it like you show in your tutorial it creates a second launcher icon and the recording only works if you start via that second icon. Any way to fix this?

**Comment by thanh-nguyen-kim** [comment]
Hi.
My plugin overrides the default Unity Main Activity so it can't be use with other plugin which do the same things like: Firebase Remote Message.
If you don't need Firebase Remote Message in your project, uninstall it and the record plugin will work as expected.
If Firebase Remote Message is a must-have plugin, you may have to follow the instruction in "Configuring a custom entry point Activity" of https://firebase.google.com/docs/cloud-messaging/unity/client then rewrite the https://github.com/thanh-nguyen-kim/Android_Screen_Recorder_Plugin project and build your own version of Unity_Android_Screen_Recorder.
Have a look at my tutorial https://killertee.wordpress.com/2018/01/08/unity-android-record-game-screen-with-audio-using-your-ad-hoc-plug-in/ . It provides useful information to step by step rebuild the record plugin.
Hope you can do it.
Best regards
Tee
