### ISSUE TITLE
"HBRecorderOnError - See Log" in some devices

### ISSUE THREAD

**Issue by Andrezinho790** [thanh-nguyen-kim/Unity_Android_Screen_Recorder#18]
In some devices I'm having this message when I click in "Record" and give the permission, when I check the gallery there is a video with error... I try to use logcat to see what is happening but no message was displayed

**Comment by thanh-nguyen-kim** [comment]
Which message was shown when you click "Record"? Have you try record using my original example? Is the record process successful with other device?

**Comment by thanh-nguyen-kim** [comment]
Interesting, can you check your logcat for full error report?

**Comment by Andrezinho790** [comment]
Its just a number "268435556"

**Comment by Andrezinho790** [comment]
I changed the encoder to "H264" and now its working !

**Comment by thanh-nguyen-kim** [comment]
Some devices only support H.264 encode. Other newer encode like Vp8, Vp9 are only supported in more recent phone.
Have a good day Andre. I will close this issue.

**Comment by iamferozi** [comment]
i tried all video formats but didn't worked.

**Comment by gianni173** [comment]
Hi, I'm having the same issue, 
- phone model Samsung Galaxy A52s 5G 
Tried all video formats but doesnt work.
