### ISSUE TITLE
Exception when opening file

### ISSUE THREAD

**Issue by fdorothy** [thanh-nguyen-kim/Unity_Android_Screen_Recorder#23]
I'm testing this on an android 27 device and seeing this error when hitting record:

`HBRecorderOnError: java.io.FileNotFoundException: /storage/emulated/0/MoviesTee/HD2022-01-11-08-39-50.mp4: open failed: ENOENT (No such file or directory)`

Any help is appreciated, thanks!

**Comment by thanh-nguyen-kim** [comment]
Hi!
Have you allowed the storage permission?

**Comment by fdorothy** [comment]
It looks like adding `AndroidUtils.RequestPermission(AndroidPermission.WRITE_EXTERNAL_STORAGE);` to `AndroidUtils.StartRecording` allows for the file to be saved to Movies. Thanks!
