### ISSUE TITLE
Doesn't start again

### ISSUE THREAD

**Issue by DwipMakwana** [thanh-nguyen-kim/Unity_Android_Screen_Recorder#29]
It starts and ends perfectly and also saves the file but it doesn't start again if I press start record.
While debugging I saw it is stuck on "preparing recorder". Any fixes?

**Comment by thanh-nguyen-kim** [comment]
Could you send the logcat when you press the start button the second time?

**Comment by DwipMakwana** [comment]
> Could you send the logcat when you press the start button the second time?

Nevermind I used your code instead and got the issue fixed thanks
