### ISSUE TITLE
Microphone audio being recorded

### ISSUE THREAD

**Issue by Evansbsr** [thanh-nguyen-kim/Unity_Android_Screen_Recorder#4]
The plugin currently records microphone audio. Is it possible to have an option for no audio?

**Comment by thanh-nguyen-kim** [comment]
It is possible to not record audio. However you will need no rewrite the android plugin a little. It is very simple so you may try yourself. If any problem occurs contact me and may we could solve it together

**Comment by gnsx** [comment]
Any chance to get mute microphone option via a function, planned update please?

**Comment by MikeBen-Hope** [comment]
Can you confirm that the application record microphone audio ? 
For me it seems no sound is recorded when I use it. 
Thanks

**Comment by thanh-nguyen-kim** [comment]
> 
> 
> Any chance to get mute microphone option via a function, planned update please?

You can have a look at https://github.com/thanh-nguyen-kim/Android_Screen_Recorder_Plugin and make your own record plugin with an on-off switch. Best regards.

> 
> 
> Can you confirm that the application record microphone audio ?
> For me it seems no sound is recorded when I use it.
> Thanks

Ofcourse, it can record microphone audio( assuming that you have already enable audio permission when  the app ask for it)
