### ISSUE TITLE
Video format or Codec

### ISSUE THREAD

**Issue by Oliro** [thanh-nguyen-kim/Unity_Android_Screen_Recorder#5]
How can I change the video format or codec ?

Thank you.

**Comment by thanh-nguyen-kim** [comment]
Hi Oliro.
Which codec do you want?
.mp4 is used because android support it very good

**Comment by Oliro** [comment]
hi, when I try to share the video in whatsapp it gives an error
"Can't send this video. choose a different video and try again".

I think it may be the codec error or not?

**Comment by thanh-nguyen-kim** [comment]
Could you open the video by tap on it? Could you share it using other social network such as twitter, facebook?

**Comment by Oliro** [comment]
yes, I can open and share video  using other social network,  only in the whatsapp don't share. 
I tested it on other devices and the problem is the same...

**Comment by thanh-nguyen-kim** [comment]
Could you check the video file size? They said that WhatApp didn't support file size larger than 25MB

**Comment by Oliro** [comment]
the error happens with any video file size.

**Comment by thanh-nguyen-kim** [comment]
It look like a whatapp problem
