### ISSUE TITLE
Stop failed :(

### ISSUE THREAD

**Issue by Naphier** [thanh-nguyen-kim/Unity_Android_Screen_Recorder#6]
`AndroidPlayer(Google_Pixel_2@192.168.1.10)</i> 20190819-19:58:59 EXCEPTION UnityEngine.AndroidJavaException: java.lang.RuntimeException: stop failed.`

Not sure why this is happening.

Full logcat:
[new 2.txt](https://github.com/thanh-nguyen-kim/Unity_Android_Screen_Recorder/files/3517467/new.2.txt)

**Comment by Naphier** [comment]
So I've done a variety of debugging and it seems on some devices that the MediaRecorder just isn't initializing. I added in the onError listener and it frequently just says MEDIA_ERROR_SERVER_DIED. Apparently Google in their infinite wisdom decided this was enough information because all the other error codes have no reference.
So this happens about 99% of the time on my Pixel 2 and Samsung 8 and 9 devices. On our LGV30 it seems to run just fine. They're all running android 8.
Maybe someone out there in the void has a clue?

**Comment by thanh-nguyen-kim** [comment]
Hi Naphier.
It look like you have the signal 11 error.
This error mostly cause by your game call to the java side up on resume from an ad network(i have the problem with Admob). You might have to delay the call to load ads, show ads for 1 second and recheck if the problem has been solved.
If the problem still occur, deleted my plugin(my plugin might cause the problem in newer android version, google change many things when release a new android version)
Have a good day.

**Comment by thanh-nguyen-kim** [comment]
have you build the example project. does it have the problem in this device?
If it cause too much pain, you can buy the "natcorder plugin" in the store. i dev my plugin before the natcorder era.

**Comment by Naphier** [comment]
Yeah, I didn't realize Natcorder now does this. We will use that. I think the issue is somewhat related to changing scenes in Unity. But once it fails even retry through the java script doesn't work. 
Thanks

**Comment by thanh-nguyen-kim** [comment]
Yep. You should avoid change scene during record. This task is very resource-intensive and will break the record process.
Best regards
Tee
